### ISSUE TITLE
Issue regading to run the application.

### ISSUE THREAD

**Issue by Connection-Point** [hungvancap/socialMedia#1]
Hi there, could you please guide me on how to launch the application sucessfully?
Because I faced an issues where i can't register a user account.

**Comment by hungvancap** [comment]
Hi, you have to set up MongoDB first then fill in the MONGO_URL variable in the .env file.
It looks like this: `mongodb+srv://username:password@cluster0.zbwfsea.mongodb.net/`
You can watch some MongoDB tutorials to get a step-by-step guide.

**Comment by Connection-Point** [comment]
> 

Yeah, I've already created the .env file with this format
```
MONGO_URL= [MyMongoDBURL]
JWT_SECRET = [MYJWTSECRET]
PORT= 5000
```

But when i try to login or register the account, it don't work. I've also checked the mongodb index and there is no insertion.

**Comment by hungvancap** [comment]
Have you added your IP in the Security > Network access tab?

**Comment by Connection-Point** [comment]
> Have you added your IP in the Security > Network access tab?

Yeah, I'm sure that I added IP into the Network Access tab, maybe we could connect using other platform if you could guide me through the issue. Thanks a lot if you kindly provide the necessary help.
